// Copyright 2017-2025 Rafael Marques Almeida. All Rights Reserved.
#pragma once
#if PLATFORM_WINDOWS
#include "Windows/AllowWindowsPlatformTypes.h"
#endif
#define IMGUI_DEFINE_MATH_OPERATORS
#include "imgui.h"
#undef IMGUI_DEFINE_MATH_OPERATORS
#include "implot.h"
#if WITH_RMAIMGUI_DEMOS
#define IMSPINNER_DEMO
#endif
#include "imspinner.h"
#if PLATFORM_WINDOWS
#include "Windows/HideWindowsPlatformTypes.h"
#endif

RMAIMGUI_API DECLARE_LOG_CATEGORY_EXTERN(LOG_RMAIMGUI, Warning, All);

#if STATS
DECLARE_STATS_GROUP(TEXT("RMAImGui"), STATGROUP_RMAIMGUI, STATCAT_Advanced);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Hooks"), STAT_HOOKS, STATGROUP_RMAIMGUI, RMAIMGUI_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Inputs"), STAT_INPUTS, STATGROUP_RMAIMGUI, RMAIMGUI_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Render"), STAT_RENDER, STATGROUP_RMAIMGUI, RMAIMGUI_API);
DECLARE_DWORD_COUNTER_STAT_EXTERN(TEXT("Batches"), STAT_BATCHES, STATGROUP_RMAIMGUI, RMAIMGUI_API);
DECLARE_DWORD_COUNTER_STAT_EXTERN(TEXT("Vertices"), STAT_VERTICES, STATGROUP_RMAIMGUI, RMAIMGUI_API);
DECLARE_DWORD_COUNTER_STAT_EXTERN(TEXT("Indices"), STAT_INDICES, STATGROUP_RMAIMGUI, RMAIMGUI_API);
DECLARE_DWORD_COUNTER_STAT_EXTERN(TEXT("Triangles"), STAT_TRIANGLES, STATGROUP_RMAIMGUI, RMAIMGUI_API);
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Resources"), STAT_RESOURCES, STATGROUP_RMAIMGUI, RMAIMGUI_API);
DECLARE_STAT(TEXT("Resources"), STAT_RESOURCES_MEMORY, STATGROUP_RMAIMGUI, EStatDataType::ST_int64, EStatFlags::ClearEveryFrame, FPlatformMemory::MCR_Physical); extern RMAIMGUI_API DEFINE_STAT(STAT_RESOURCES_MEMORY);
DECLARE_STAT(TEXT("Resources In Use"), STAT_RESOURCES_IN_USE_MEMORY, STATGROUP_RMAIMGUI, EStatDataType::ST_int64, EStatFlags::ClearEveryFrame, FPlatformMemory::MCR_Physical); extern RMAIMGUI_API DEFINE_STAT(STAT_RESOURCES_IN_USE_MEMORY);
#endif

#define RMAIMGUI_LIBRARY !RMAIMGUI_DEVELOPMENTONLY || !(UE_BUILD_SHIPPING || UE_BUILD_TEST)
